# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3bd238013565ccf368adff782d14e14a6f2fbee841b786ea1974024933b75ba0555b5cc7b3b2d0bde5e6765d6d07d4fc592bd168b14436062dce8c1cfef7f81a

test:
  secret_key_base: 84077e6cbd8cd69351c4915e3489c6e7ce4ce17bde305e8b1db2e53cce7d0ef0257ac174eda39b7480ff32b90f4a93ed7f8d28dfee32266f6bd7f6aba3f2af45

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
